import nodemailer from "nodemailer";
import dotenv from "dotenv";

dotenv.config();

const transporter = nodemailer.createTransport({
    service: "gmail",
    auth: {
        user: process.env.EMAIL_USER,
        pass: process.env.EMAIL_PASS,
    },
});

export interface ProcessedNotice {
    title: string;
    author: string;
    date: string;
    url: string;
    htmlContent: string;
}

export async function sendNoticeEmail(
    notices: ProcessedNotice[]
): Promise<void> {
    if (notices.length === 0) {
        console.log("📭 No new notices to send.");
        return;
    }

    const html = `
    < !DOCTYPE html >
        <html>
        <head>
        <meta charset="UTF-8" >
            <title>GNDEC Latest Notices </title>
                </head>
                < body style = "font-family: Arial, Helvetica, sans-serif; background:#f5f5f5; padding:20px;" >

                    <div style="max-width:800px;margin:auto;background:#ffffff;padding:25px;border-radius:10px;" >

                        <h2 style="color:#0d6efd;" >
📢 Latest GNDEC Notifications
    </h2>

    <p>
The following new notifications were recently published on the GNDEC Notice Board.
</p>

${
    notices
        .map(
            (notice) => `
<div style="border:1px solid #ddd;border-radius:8px;padding:16px;margin-bottom:20px;">

${notice.htmlContent}

<p style="margin-top:15px;">
<strong>Department:</strong> ${notice.author}<br>
<strong>Date:</strong> ${notice.date}
</p>

<p>
<a href="${notice.url}" target="_blank">
Read Full Notice →
</a>
</p>

</div>
`
        )
    .join("")
}

<hr>

    <p style="font-size:12px;color:#666;" >
        This email was automatically generated by the InfoCascade Notification Agent.
</p>

            </div>

            </body>
            </html>
                `;

    await transporter.sendMail({
        from: process.env.EMAIL_USER,
        to: process.env.RECIPIENT_EMAIL,
        subject: `📢 ${ notices.length } New GNDEC Notification${
    notices.length > 1 ? "s" : ""
} `,
        html,
    });

    console.log(`✅ Email sent successfully(${ notices.length } notification${ notices.length > 1 ? "s" : "" }).`);
}